import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getCurrentProfile } from "@/lib/auth";
import type { AdminReports } from "@/types/database";

const ranges = { today: 1, "7d": 7, "30d": 30, "90d": 90 } as const;
type RangeKey = keyof typeof ranges;
function startFor(range: RangeKey) { const start = new Date(); start.setHours(0, 0, 0, 0); start.setDate(start.getDate() - (ranges[range] - 1)); return start; }
function fmt(value: number) { return value.toLocaleString("en-NG"); }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function BarList({ title, items }: { title: string; items: { label: string; value: number }[] }) { const max = Math.max(...items.map((item) => item.value), 1); return <article className="card" style={{ padding: 24 }}><p className="eyebrow" style={{ marginTop: 0 }}>{title}</p><div style={{ display: "grid", gap: 14, marginTop: 18 }}>{items.map((item) => <div key={item.label}><div style={{ display: "flex", justifyContent: "space-between", gap: 12, fontSize: 13, marginBottom: 6 }}><span style={{ textTransform: "capitalize" }}>{label(item.label)}</span><strong>{fmt(item.value)}</strong></div><div style={{ height: 9, background: "#e5e7eb", borderRadius: 999, overflow: "hidden" }}><div style={{ width: `${Math.max((item.value / max) * 100, item.value ? 4 : 0)}%`, height: "100%", background: "var(--ink)", borderRadius: 999 }} /></div></div>)}</div></article>; }
function Trend({ title, data }: { title: string; data: { date: string; count: number }[] }) { const max = Math.max(...data.map((item) => item.count), 1); const points = data.length ? data.map((item, index) => `${(index / Math.max(data.length - 1, 1)) * 100},${100 - (item.count / max) * 86}`).join(" ") : "0,100 100,100"; return <article className="card" style={{ padding: 24 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}><p className="eyebrow" style={{ margin: 0 }}>{title}</p><span style={{ color: "var(--muted)", fontSize: 12 }}>{data.length} active days</span></div><div style={{ position: "relative", height: 170, marginTop: 18, borderBottom: "1px solid #e5e7eb" }}>{data.length ? <svg viewBox="0 0 100 100" preserveAspectRatio="none" style={{ width: "100%", height: "100%" }} role="img" aria-label={`${title} trend`}><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg> : <p style={{ color: "var(--muted)" }}>No activity in this period.</p>}</div><div style={{ display: "flex", justifyContent: "space-between", color: "var(--muted)", fontSize: 11, marginTop: 8 }}><span>{data[0]?.date ?? "—"}</span><span>{data[data.length - 1]?.date ?? "—"}</span></div></article>; }

export default async function AdministratorReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const profile = await getCurrentProfile();
  if (profile.role !== "administrator") redirect(`/dashboard/${profile.role}`);
  const params = await searchParams;
  const requested = Array.isArray(params.range) ? params.range[0] : params.range;
  const requestedFrom = Array.isArray(params.from) ? params.from[0] : params.from;
  const requestedTo = Array.isArray(params.to) ? params.to[0] : params.to;
  const customFrom = requestedFrom ? new Date(`${requestedFrom}T00:00:00`) : null;
  const customTo = requestedTo ? new Date(`${requestedTo}T23:59:59.999`) : null;
  const hasCustom = Boolean(customFrom && customTo && !Number.isNaN(customFrom.getTime()) && !Number.isNaN(customTo.getTime()) && customFrom < customTo);
  const range: RangeKey = requested && requested in ranges ? requested as RangeKey : "30d";
  const from = hasCustom ? customFrom as Date : startFor(range);
  const to = hasCustom ? customTo as Date : new Date();
  const supabase = await createClient();
  const { data, error } = await supabase.rpc("get_admin_reports", { p_from: from.toISOString(), p_to: to.toISOString() });
  if (error) throw new Error("Unable to load administrator reports.");
  const report = data as unknown as AdminReports;
  const exportHref = `/dashboard/administrator/reports/export?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`;
  const periodCards = [["New users", report.period_activity.new_users], ["Assessments created", report.period_activity.assessments_created], ["Submissions", report.period_activity.submissions_created], ["Verifications", report.period_activity.verifications_created], ["Opportunities", report.period_activity.opportunities_created], ["Applications", report.period_activity.applications_created]] as const;
  const filterHref = (key: RangeKey) => `/dashboard/administrator/reports?range=${key}`;
  const userRoleItems = Object.entries(report.user_roles).map(([key, value]) => ({ label: String(key), value: Number(value) }));
  const submissionStatusItems = Object.entries(report.submissions).map(([name, value]) => ({ label: String(name), value: Number(value) }));
  const applicationStatusItems = Object.entries(report.applications).filter(([name]) => name !== "acceptance_rate").map(([name, value]) => ({ label: String(name), value: Number(value) }));
  const opportunityTypeItems = Object.entries(report.opportunities).filter(([name]) => ["jobs", "internships", "apprenticeships", "volunteer"].includes(name)).map(([name, value]) => ({ label: String(name), value: Number(value) }));
  const skillCategoryItems = report.skills_by_category.map((item) => ({ label: item.category, value: item.skills }));
  return <div style={{ display: "grid", gap: 24 }}>
    <section><div style={{ display: "flex", justifyContent: "space-between", gap: 18, flexWrap: "wrap", alignItems: "end" }}><div><p className="eyebrow">Administrator reports</p><h1 style={{ fontSize: "clamp(2rem,5vw,3.5rem)", letterSpacing: "-.045em", margin: "10px 0" }}>Reports & analytics</h1><p style={{ color: "var(--muted)", fontSize: 17, maxWidth: 760 }}>A permission-protected view of platform growth, assessment activity, verification health, and security signals.</p></div><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{(Object.keys(ranges) as RangeKey[]).map((key) => <Link key={key} className={`button ${!hasCustom && range === key ? "" : "secondary"}`} href={filterHref(key)}>{key === "today" ? "Today" : key.toUpperCase()}</Link>)}<Link className="button secondary" href={exportHref}>Export CSV</Link></div></div></section>
    <section className="card" style={{ padding: 20 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 16, flexWrap: "wrap", alignItems: "center" }}><div><p className="eyebrow" style={{ margin: 0 }}>Custom period</p><p style={{ margin: "6px 0 0", color: "var(--muted)", fontSize: 13 }}>Use a specific date range when the preset windows are not enough.</p></div><form method="get" style={{ display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" }}><input type="date" name="from" defaultValue={hasCustom ? requestedFrom : ""} aria-label="Report start date" required /><span style={{ color: "var(--muted)" }}>to</span><input type="date" name="to" defaultValue={hasCustom ? requestedTo : ""} aria-label="Report end date" required /><button className="button" type="submit">Apply</button></form></div></section>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 14 }}>{periodCards.map(([name, value]) => <article className="card" style={{ padding: 20 }} key={name}><p style={{ margin: 0, color: "var(--muted)", fontSize: 13 }}>{name}</p><strong style={{ display: "block", fontSize: 30, marginTop: 6 }}>{fmt(value)}</strong><p style={{ margin: "6px 0 0", color: "var(--muted)", fontSize: 12 }}>Selected period</p></article>)}</section>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 14 }}>{[["Total users", report.overview.users], ["Learners", report.overview.learners], ["Mentors", report.overview.mentors], ["Employers", report.overview.employers], ["Verified skills", report.overview.verified_skills], ["Active accounts", report.overview.active_users], ["Suspended accounts", report.overview.suspended_users], ["Assessments", report.overview.assessments]].map(([name, value]) => <article className="card" style={{ padding: 18 }} key={String(name)}><span style={{ color: "var(--muted)", fontSize: 12 }}>{name}</span><strong style={{ display: "block", fontSize: 26, marginTop: 5 }}>{fmt(value as number)}</strong></article>)}</section>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 16 }}><BarList title="Users by role" items={userRoleItems} /><BarList title="Verification decisions" items={[["approved", report.verification.approved], ["rejected", report.verification.rejected], ["revision_requested", report.verification.revision_requested]].map(([name, value]) => ({ label: String(name), value: Number(value) }))} /><BarList title="Verification status" items={[["active", report.verification.active], ["suspended", report.verification.suspended], ["revoked", report.verification.revoked]].map(([name, value]) => ({ label: String(name), value: Number(value) }))} /><BarList title="Submission status" items={submissionStatusItems} /><BarList title="Application status" items={applicationStatusItems} /><BarList title="Opportunity types" items={opportunityTypeItems} /><BarList title="Skills by category" items={skillCategoryItems} /></section>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 16 }}><Trend title="User registrations" data={report.user_trend} /><Trend title="Verification activity" data={report.verification_trend} /><Trend title="Submission activity" data={report.submission_trend} /><Trend title="Application activity" data={report.application_trend} /></section>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 16 }}>
      <article className="card" style={{ padding: 24 }}><p className="eyebrow" style={{ marginTop: 0 }}>Employer activity</p><div style={{ display: "grid", gap: 12, marginTop: 18 }}>{[["Active employers", report.employer_activity.active_employers], ["Opportunities created", report.employer_activity.opportunities_created], ["Published opportunities", report.employer_activity.published_opportunities], ["Applications received", report.employer_activity.applications_received]].map(([name, value]) => <div key={String(name)} style={{ display: "flex", justifyContent: "space-between" }}><span>{name}</span><strong>{fmt(value as number)}</strong></div>)}</div></article>
      <article className="card" style={{ padding: 24 }}><p className="eyebrow" style={{ marginTop: 0 }}>Mentor activity</p><div style={{ display: "grid", gap: 12, marginTop: 18 }}>{[["Active mentors", report.mentor_activity.active_mentors], ["Reviews recorded", report.mentor_activity.reviews_recorded], ["Approved reviews", report.mentor_activity.approved_reviews], ["Average rating", report.mentor_activity.average_rating]].map(([name, value]) => <div key={String(name)} style={{ display: "flex", justifyContent: "space-between" }}><span>{name}</span><strong>{fmt(value as number)}</strong></div>)}</div></article>
      <article className="card" style={{ padding: 24 }}><p className="eyebrow" style={{ marginTop: 0 }}>Learner outcomes</p><div style={{ display: "grid", gap: 12, marginTop: 18 }}>{[["Learners with submissions", report.learner_outcomes.learners_with_submissions], ["Learners verified", report.learner_outcomes.learners_verified], ["Learners with applications", report.learner_outcomes.learners_with_applications], ["Learners accepted", report.learner_outcomes.learners_accepted], ["Verified → application rate", report.learner_outcomes.verified_to_application_rate]].map(([name, value]) => <div key={String(name)} style={{ display: "flex", justifyContent: "space-between" }}><span>{name}</span><strong>{fmt(value as number)}{String(name).includes("rate") ? "%" : ""}</strong></div>)}</div></article>
      <article className="card" style={{ padding: 24 }}><p className="eyebrow" style={{ marginTop: 0 }}>Application outcomes</p><strong style={{ fontSize: 44 }}>{report.applications.acceptance_rate.toFixed(2)}<span style={{ fontSize: 20, color: "var(--muted)" }}>%</span></strong><p style={{ color: "var(--muted)" }}>Acceptance rate for applications created in the selected period.</p><p style={{ margin: 0 }}><strong>{fmt(report.applications.accepted)}</strong> accepted of <strong>{fmt(report.applications.total)}</strong> applications.</p></article>
    </section>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 16 }}><article className="card" style={{ padding: 24 }}><p className="eyebrow" style={{ marginTop: 0 }}>Security insights</p><div style={{ display: "grid", gap: 12, marginTop: 18 }}>{[["Audit events", report.security.audit_events], ["Successful logins", report.security.successful_logins], ["Failed logins", report.security.failed_logins], ["Security events", report.security.security_events], ["Permission changes", report.security.permission_changes], ["Administrator actions", report.security.admin_actions]].map(([name, value]) => <div key={String(name)} style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #eef2f7", paddingBottom: 10 }}><span>{name}</span><strong>{fmt(value as number)}</strong></div>)}</div></article><article className="card" style={{ padding: 24 }}><p className="eyebrow" style={{ marginTop: 0 }}>Verification quality</p><strong style={{ fontSize: 44 }}>{report.verification.average_rating.toFixed(2)}<span style={{ fontSize: 20, color: "var(--muted)" }}>/5</span></strong><p style={{ color: "var(--muted)" }}>Average competency rating for verifications recorded in the selected period.</p><Link className="button secondary" href="/dashboard/administrator/verifications">Open verification center</Link></article></section>
    <section className="card" style={{ padding: 24 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" }}><div><p className="eyebrow" style={{ margin: 0 }}>Administrative activity</p><h2 style={{ margin: "8px 0 0" }}>Recent events in period</h2></div><Link className="button secondary" href="/dashboard/administrator/audit">Open audit center</Link></div><div style={{ display: "grid", gap: 10, marginTop: 18 }}>{report.recent_admin_activity.length ? report.recent_admin_activity.map((event, index) => <div key={`${event.created_at}-${index}`} style={{ display: "flex", justifyContent: "space-between", gap: 16, paddingBlock: 12, borderTop: "1px solid #eef2f7" }}><div><strong>{label(event.action)}</strong><p style={{ margin: "4px 0 0", color: "var(--muted)", fontSize: 13 }}>{event.description}</p></div><time style={{ color: "var(--muted)", fontSize: 12, whiteSpace: "nowrap" }}>{new Date(event.created_at).toLocaleDateString("en-NG", { day: "2-digit", month: "short" })}</time></div>) : <p style={{ color: "var(--muted)" }}>No administrative events recorded in this period.</p>}</div></section>
    <section className="notice"><strong>Access control:</strong> report data is returned by a database function that requires the existing <code>reports.view</code> administrator permission. CSV export uses the same authorization check.</section>
  </div>;
}
